----  VALORANT NORECOIL Phantom, Vandal, Bulldog and Spectre Aim 0.75 and Mult 0.80 SENS ----
-- Version 1.0.0 (New No recoil code)
------------------------------------------------------------------------------------------
-- ***** CONSTANTS FOR SENS ADJUSTMENT *****
--
-- Here you can adjust values for each weapon. You should increase or decrease the values
-- according to choosen sensibility. When in game the correct value set here wil produce the 
-- norecoil effect for the choosen weapon
-- 
-- The value 1.0 is default for Sens 0.75 and Scoped Mult 0.80.
--
-- Note: first copy this file with a different name (preferable a name that indicates the choosen 
-- sens), so this default one does not get messed.
------------------------------------------------------------------------------------------
local phantomConstant=1.0
local vandalConstant=1.0
local bulldogConstant=1.0
local spectreConstant=1.0
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
local Activate = 3		-- default pressing the wheel
local recoil = false	-- Disable/Enable no recoil

EnablePrimaryMouseButtonEvents(true)

function OnEvent(event, arg)
	if (event == "MOUSE_BUTTON_PRESSED" and arg == Activate) then
		recoil = not recoil
		if (recoil == false) then
		  OutputLogMessage("OFF-NoRecoil\n")
		  OutputLCDMessage("OFF-NoRecoil") 
		else
		  OutputLogMessage("ON-NoRecoil\n")
		  OutputLCDMessage("ON-NoRecoil") 
		end
	end
	if recoil then
		-- Weapon selection
		if(IsKeyLockOn('capslock'))then
			if IsKeyLockOn('scrolllock') then
                Spectre()
			else
				Phantom()
			end
        else
            if IsKeyLockOn('scrolllock') then
                Bulldog()
            else
			    Vandal()
            end
        end
    end
end
------------------------------------------------------------------------
function Phantom()
       repeat
              Sleep(24)
       if not IsMouseButtonPressed(1) then break end
              MoveMouseRelative(0,4*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,4*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,4*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,4*phantomConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,4*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,4*phantomConstant)
              MoveMouseRelative(0,4*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,4*phantomConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              Sleep(24)
              MoveMouseRelative(0,5*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,5*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,5*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,6*phantomConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,6*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,7*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,7*phantomConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,8*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,9*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,9*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,8*phantomConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,7*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,4*phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,phantomConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,phantomConstant)
              Sleep(24)
              MoveMouseRelative(0,phantomConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(10*phantomConstant,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(10*phantomConstant,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative((-10)*phantomConstant,0)
              Sleep(24)
              MoveMouseRelative(0,0) 
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative((-10)*phantomConstant,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
      if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
                MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0) 
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              if not IsMouseButtonPressed(1) then break end
              Sleep(96)
              if not IsMouseButtonPressed(1) then break end
              Sleep(960)
              if not IsMouseButtonPressed(1) then break end
       until not IsMouseButtonPressed(1)
end
------------------------------------------------------------------------
function Vandal()
       repeat
              Sleep(24)
       if not IsMouseButtonPressed(1) then break end
              MoveMouseRelative(0,4*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,4*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,4*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,4*vandalConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,4*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,4*vandalConstant)
              MoveMouseRelative(0,4*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,4*vandalConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              Sleep(24)
              MoveMouseRelative(0,5*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,5*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,6*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,6*vandalConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,6*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,6*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,6*vandalConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,8*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,10*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,10*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,8*vandalConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,8*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,7*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,7*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,5*vandalConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,2*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,2*vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(10*vandalConstant,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(10*vandalConstant,vandalConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative((-10)*vandalConstant,0)
              Sleep(24)
              MoveMouseRelative(0,0)  
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative((-10)*vandalConstant,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
      if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
                MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
              Sleep(24)
              MoveMouseRelative(0,vandalConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)  
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              if not IsMouseButtonPressed(1) then break end
              Sleep(96)
              if not IsMouseButtonPressed(1) then break end
              Sleep(960)
              if not IsMouseButtonPressed(1) then break end
             until not IsMouseButtonPressed(1)
end
------------------------------------------------------------------------
function Spectre()    
       repeat
              Sleep(24)
       if not IsMouseButtonPressed(1) then break end
              MoveMouseRelative(0,2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,4*spectreConstant)
              MoveMouseRelative(0,4*spectreConstant)
              Sleep(24)
              Sleep(24)
              MoveMouseRelative(0,4*spectreConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,5*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,7*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,7*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,5*spectreConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,4*spectreConstant)
              Sleep(24)
              MoveMouseRelative((-3)*spectreConstant,4*spectreConstant)
              Sleep(24)
              MoveMouseRelative((-3)*spectreConstant,4*spectreConstant)
              Sleep(24)
              MoveMouseRelative((-3)*spectreConstant,4*spectreConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,3*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,(-2)*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,(-2)*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,(-2)*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(5*spectreConstant,0)
              Sleep(24)
              MoveMouseRelative(6*spectreConstant,0)
              Sleep(24)
              MoveMouseRelative(5*spectreConstant,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
      if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative((-3)*spectreConstant,spectreConstant)
              Sleep(24)
              MoveMouseRelative((-4)*spectreConstant,0)
              Sleep(24)
              MoveMouseRelative((-5)*spectreConstant,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
                MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,spectreConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              if not IsMouseButtonPressed(1) then break end
              Sleep(96)
              if not IsMouseButtonPressed(1) then break end
              Sleep(960)
              if not IsMouseButtonPressed(1) then break end
         until not IsMouseButtonPressed(1)
end
------------------------------------------------------------------------
function Bulldog()
       repeat
              Sleep(24)
       if not IsMouseButtonPressed(1) then break end
              MoveMouseRelative(0,2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,2*bulldogConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,3*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,3*bulldogConstant)
              MoveMouseRelative(0,3*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,3*bulldogConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              Sleep(24)
              MoveMouseRelative(0,3*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,4*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,4*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,4*bulldogConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,4*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,4*bulldogConstant)
              MoveMouseRelative(0,4*bulldogConstant)
              Sleep(24)
              Sleep(24)
              MoveMouseRelative(0,4*bulldogConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,5*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,5*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,6*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,7*bulldogConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,7*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,5*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,4*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,4*bulldogConstant)
              if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,3*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,3*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,3*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,3*bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,3*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(6*bulldogConstant,0)
              Sleep(24)
              MoveMouseRelative(6*bulldogConstant,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative((-4)*bulldogConstant,0.1*bulldogConstant)
              Sleep(24)
              MoveMouseRelative((-4)*bulldogConstant,0.1*bulldogConstant)
              Sleep(24)
              MoveMouseRelative((-4)*bulldogConstant,0.1*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.1*bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
      if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
                MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,0.2*bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
               MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
              Sleep(24)
              MoveMouseRelative(0,bulldogConstant)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0) 
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
       if not IsMouseButtonPressed(1) then break end
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              Sleep(24)
              MoveMouseRelative(0,0)
              if not IsMouseButtonPressed(1) then break end
              Sleep(96)
              if not IsMouseButtonPressed(1) then break end
              Sleep(960)
              if not IsMouseButtonPressed(1) then break end
              until not IsMouseButtonPressed(1)
end