----  VALORANT NORECOIL Phantom, Vandal, Bulldog and Spectre  SENS ----
-- Version 1.0.0 (New No recoil code)
------------------------------------------------------------------------------------------
-- ***** CONSTANTS FOR SENS ADJUSTMENT *****
--
-- Here you can adjust values for each weapon. You should increase or decrease the values
-- according to choosen sensibility. When in game the correct value set here wil produce the 
-- norecoil effect for the choosen weapon
-- 
-- The value 1.0 is default for Sens 1,00 and Scoped Mult 1,00
--
-- Note: first copy this file with a different name (preferable a name that indicates the choosen 
-- sens), so this default one does not get messed.
------------------------------------------------------------------------------------------
local phantomConstant=0.85
local vandalConstant=0.85
local bulldogConstant=0.85
local spectreConstant=0.95
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
local Activate = 3		-- default pressing the wheel
local recoil = false	-- Disable/Enable no recoil

EnablePrimaryMouseButtonEvents(true)

function OnEvent(event, arg)
	if (event == "MOUSE_BUTTON_PRESSED" and arg == Activate) then
		recoil = not recoil
		if (recoil == false) then
		  OutputLogMessage("OFF-NoRecoil\n")
		  OutputLCDMessage("OFF-NoRecoil") 
		else
		  OutputLogMessage("ON-NoRecoil\n")
		  OutputLCDMessage("ON-NoRecoil") 
		end
	end
	if recoil then
		-- Weapon selection --
		if(IsKeyLockOn('capslock'))then
			if IsKeyLockOn('scrolllock') then
                Spectre()
			else
				Phantom()
			end
        else
            if IsKeyLockOn('scrolllock') then
                Bulldog()
            else
			    Vandal()
            end
        end
    end
end
------------------------------------------------------------------------
function Phantom()
       repeat
	   Sleep(24)
if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,4)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,5)
        Sleep(24)
        MoveMouseRelative(0,6)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,6)
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,7)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,8)
        Sleep(24)
        MoveMouseRelative(0,9)
        Sleep(24)
        MoveMouseRelative(0,9)
        Sleep(24)
        MoveMouseRelative(0,8)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,7)
        Sleep(24)
        MoveMouseRelative(0,4)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(10,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(10,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(-10,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-10,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
 until not IsMouseButtonPressed(1)
     end
------------------------------------------------------------------------
function Vandal()
       repeat
				Sleep(24)
		if not IsMouseButtonPressed(1) then break end
				MoveMouseRelative(0,4)
					Sleep(24)
				MoveMouseRelative(0,4)
				Sleep(24)
				MoveMouseRelative(0,4)
				Sleep(24)
				MoveMouseRelative(0,4)
				if not IsMouseButtonPressed(1) then break end
				Sleep(24)
				MoveMouseRelative(0,4)
				Sleep(24)
				MoveMouseRelative(0,4)
				MoveMouseRelative(0,4)
				Sleep(24)
				MoveMouseRelative(0,4)
				if not IsMouseButtonPressed(1) then break end
				Sleep(24)
				Sleep(24)
				MoveMouseRelative(0,5)
				Sleep(24)
				MoveMouseRelative(0,5)
				Sleep(24)
				MoveMouseRelative(0,6)
				Sleep(24)
				MoveMouseRelative(0,6)
				if not IsMouseButtonPressed(1) then break end
				Sleep(24)
				MoveMouseRelative(0,6)
				Sleep(24)
				MoveMouseRelative(0,6)
				Sleep(24)
				MoveMouseRelative(0,6)
				if not IsMouseButtonPressed(1) then break end
				Sleep(24)
				MoveMouseRelative(0,8)
				Sleep(24)
				MoveMouseRelative(0,10)
				Sleep(24)
				MoveMouseRelative(0,10)
				Sleep(24)
				MoveMouseRelative(0,8)
				if not IsMouseButtonPressed(1) then break end
				Sleep(24)
					MoveMouseRelative(0,8)
					Sleep(24)
					MoveMouseRelative(0,7)
					Sleep(24)
					MoveMouseRelative(0,7)
					Sleep(24)
					MoveMouseRelative(0,5)
				if not IsMouseButtonPressed(1) then break end
					Sleep(24)
					MoveMouseRelative(0,2)
					Sleep(24)
					MoveMouseRelative(0,2)
					Sleep(24)
					MoveMouseRelative(0,1)
					Sleep(24)
					MoveMouseRelative(0,1)
				if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(10,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(10,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(-10,0)
        Sleep(24)
        MoveMouseRelative(0,0) 
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(-10,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
          MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
         MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
        Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0) 
        Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
       until not IsMouseButtonPressed(1)
end
------------------------------------------------------------------------
function Spectre()    
       repeat
            Sleep(24)
 if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,2)
			Sleep(24)
        MoveMouseRelative(0,2)
			Sleep(24)
        MoveMouseRelative(0,2)
			Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,4)
        MoveMouseRelative(0,4)
			Sleep(24)
			Sleep(24)
        MoveMouseRelative(0,4)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,5)
			Sleep(24)
        MoveMouseRelative(0,7)
			Sleep(24)
        MoveMouseRelative(0,7)
			Sleep(24)
        MoveMouseRelative(0,5)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,4)
			Sleep(24)
        MoveMouseRelative(-3,4)
			Sleep(24)
        MoveMouseRelative(-3,4)
			Sleep(24)
        MoveMouseRelative(-3,4)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
		MoveMouseRelative(0,-2)
			Sleep(24)
        MoveMouseRelative(0,-2)
			Sleep(24)
        MoveMouseRelative(0,-2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
		MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
		MoveMouseRelative(5,0)
			Sleep(24)
        MoveMouseRelative(6,0)
			Sleep(24)
        MoveMouseRelative(6,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(-3,1)
			Sleep(24)
        MoveMouseRelative(-4,0)
			Sleep(24)
        MoveMouseRelative(-5,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
		MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
   until not IsMouseButtonPressed(1)
     end
------------------------------------------------------------------------
function Bulldog()
       repeat
              Sleep(24)
	if not IsMouseButtonPressed(1) then break end
        MoveMouseRelative(0,2)
			Sleep(24)
        MoveMouseRelative(0,2)
			Sleep(24)
        MoveMouseRelative(0,2)
			Sleep(24)
        MoveMouseRelative(0,2)
	if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
        if not IsMouseButtonPressed(1) then break end
			Sleep(24)
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,4)
			Sleep(24)
        MoveMouseRelative(0,4)
			Sleep(24)
        MoveMouseRelative(0,4)
	if not IsMouseButtonPressed(1) then break end
        Sleep(24)
			MoveMouseRelative(0,4)
			Sleep(24)
        MoveMouseRelative(0,4)
        MoveMouseRelative(0,4)
			Sleep(24)
			Sleep(24)
        MoveMouseRelative(0,4)
    if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,5)
			Sleep(24)
        MoveMouseRelative(0,5)
			Sleep(24)
        MoveMouseRelative(0,6)
			Sleep(24)
        MoveMouseRelative(0,7)
        if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,7)
			Sleep(24)
        MoveMouseRelative(0,5)
			Sleep(24)
        MoveMouseRelative(0,4)
			Sleep(24)
        MoveMouseRelative(0,4)
        if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,3)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,3)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(6,0)
			Sleep(24)
        MoveMouseRelative(6,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(-4,0.1)
			Sleep(24)
        MoveMouseRelative(-4,0.1)
			Sleep(24)
        MoveMouseRelative(-4,0.1)
			Sleep(24)
        MoveMouseRelative(0,0.1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
			Sleep(24)
        MoveMouseRelative(0,0.2)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
			Sleep(24)
        MoveMouseRelative(0,1)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0) 
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
		MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
 if not IsMouseButtonPressed(1) then break end
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
			Sleep(24)
        MoveMouseRelative(0,0)
        if not IsMouseButtonPressed(1) then break end
        Sleep(96)
        if not IsMouseButtonPressed(1) then break end
        Sleep(960)
        if not IsMouseButtonPressed(1) then break end
        until not IsMouseButtonPressed(1)
     end
